# Generated by Django 5.2.7 on 2025-11-06 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameTableModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("game_name", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_event_sequence_number", models.IntegerField(default=0)),
                ("snapshot", models.JSONField()),
                (
                    "owner",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "gametable",
            },
        ),
        migrations.CreateModel(
            name="GameStateSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_sequence_number", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField()),
                (
                    "game_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_state_snapshots",
                        to="gametables.gametablemodel",
                    ),
                ),
            ],
            options={
                "db_table": "gamestate_snapshot",
                "ordering": ["event_sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="GameEventModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence_number", models.IntegerField()),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("schema_version", models.IntegerField(default=1)),
                (
                    "game_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_events",
                        to="gametables.gametablemodel",
                    ),
                ),
            ],
            options={
                "db_table": "gameevent",
                "ordering": ["sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="GameConfigModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("config_key", models.CharField(max_length=100)),
                ("value", models.JSONField()),
                (
                    "game_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_configs",
                        to="gametables.gametablemodel",
                    ),
                ),
            ],
            options={
                "db_table": "gametable_gameconfig",
            },
        ),
        migrations.CreateModel(
            name="PlayerModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("screen_name", models.CharField(max_length=50)),
                ("bot_strategy_kind", models.CharField(max_length=50, null=True)),
                (
                    "game_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="gametables.gametablemodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "gametable_player",
            },
        ),
        migrations.CreateModel(
            name="TableConfigModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("config_key", models.CharField(max_length=100)),
                ("value", models.JSONField()),
                (
                    "game_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_configs",
                        to="gametables.gametablemodel",
                    ),
                ),
            ],
            options={
                "db_table": "gametable_tableconfig",
            },
        ),
        migrations.AddIndex(
            model_name="gametablemodel",
            index=models.Index(fields=["game_name", "status"], name="game_name_status_index"),
        ),
        migrations.AddIndex(
            model_name="gamestatesnapshot",
            index=models.Index(fields=["game_table", "event_sequence_number"], name="snapshot_table_event_seq_idx"),
        ),
        migrations.AddConstraint(
            model_name="gamestatesnapshot",
            constraint=models.UniqueConstraint(
                fields=("game_table", "event_sequence_number"), name="uniq_snapshot_event_seq_per_table"
            ),
        ),
        migrations.AddIndex(
            model_name="gameeventmodel",
            index=models.Index(fields=["game_table", "sequence_number"], name="event_table_seq_idx"),
        ),
        migrations.AddConstraint(
            model_name="gameeventmodel",
            constraint=models.UniqueConstraint(
                fields=("game_table", "sequence_number"), name="uniq_event_seq_per_table"
            ),
        ),
        migrations.AddConstraint(
            model_name="gameconfigmodel",
            constraint=models.UniqueConstraint(
                fields=("game_table", "config_key"), name="uniq_game_config_key_per_table"
            ),
        ),
        migrations.AddConstraint(
            model_name="playermodel",
            constraint=models.UniqueConstraint(
                fields=("game_table", "screen_name"), name="uniq_player_screen_name_per_table"
            ),
        ),
        migrations.AddConstraint(
            model_name="playermodel",
            constraint=models.UniqueConstraint(fields=("game_table", "user"), name="uniq_player_user_per_table"),
        ),
        migrations.AddConstraint(
            model_name="tableconfigmodel",
            constraint=models.UniqueConstraint(
                fields=("game_table", "config_key"), name="uniq_table_config_key_per_table"
            ),
        ),
    ]
