# Generated by Django 5.2.7 on 2025-10-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gametables", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gametablesnapshot",
            name="last_event_sequence_number",
            field=models.IntegerField(default=0),
        ),
    ]
