LARGE_MARRIAGE_POINTS = 40
SMALL_MARRIAGE_POINTS = 20

CARDS_IN_STARTING_HAND = 7
CARDS_TO_TAKE = 3

GAME_STARTING_POINTS = 500
NOT_ALLOWED_TO_BID_THRESHOLD = 1000
MUST_BID_THRESHOLD = 100
MAX_BID = 200
MAX_BID_NO_MARRIAGE = 120
MIN_BID = 60
BID_STEP = 5

EMPTY_HAND_SIZE = 0
MAX_SEATS = 3
MIN_SEATS = 3
